import { HttpStatus } from '@nestjs/common';
import { ApiProperty, ApiSchema } from '@nestjs/swagger';
import { Expose } from 'class-transformer';
import { IsInt, IsString } from 'class-validator';

@ApiSchema({ name: 'Problem Response' })
export class ProblemResponseDto {
  @ApiProperty({
    description: 'A short, human-readable summary of the problem type.',
    example: 'COMPANY_NOT_FOUND',
  })
  @IsString()
  @Expose()
  title: string;

  @ApiProperty({
    description:
      'The HTTP status code generated by the origin server for this occurrence of the problem.',
    example: HttpStatus.UNPROCESSABLE_ENTITY,
  })
  @IsInt()
  @Expose()
  status: HttpStatus;

  @ApiProperty({
    description:
      'A human-readable explanation specific to this occurrence of the problem.',
    example: 'Company with id a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d not found',
  })
  @IsString()
  @Expose()
  detail: string;

  @ApiProperty({
    description:
      'A URI reference that identifies the specific occurrence of the problem.',
    example: '/v1/transfers',
  })
  @IsString()
  @Expose()
  instance: string;
}
